### ISSUE TITLE
跑起来的时候报错，作者大佬帮忙看下

### ISSUE THREAD

**Issue by yj229201093** [MrLiuYS/lcfarm_flutter_umeng#14]
MissingPluginException(No implementation found for method init on channel lcfarm_flutter_umeng)
E/flutter ( 4246): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 4246): <asynchronous suspension>
E/flutter ( 4246): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 4246): #2      LcfarmFlutterUmeng.init (package:lcfarm_flutter_umeng/lcfarm_flutter_umeng.dart:32:20)

**Comment by Blankeer** [comment]
+1

**Comment by bigtotorouk** [comment]
+1

**Comment by MrLiuYS** [comment]
你好.由于最近换了工作.天天加班.改动了没有注意测试.导致出现问题.可以试试用另外一个大佬写的 https://github.com/flmn/umeng_analytics_plugin

**Comment by MrLiuYS** [comment]
你好.由于最近换了工作.天天加班.改动了没有注意测试.导致出现问题.可以试试用另外一个大佬写的 https://github.com/flmn/umeng_analytics_plugin , 
可以试试用0.1.8的版本
  lcfarm_flutter_umeng:
    git:
      url: https://github.com/MrLiuYS/lcfarm_flutter_umeng.git
      ref: 0.1.8
很抱歉.添麻烦了.

**Comment by yj229201093** [comment]
> 你好.由于最近换了工作.天天加班.改动了没有注意测试.导致出现问题.可以试试用另外一个大佬写的 https://github.com/flmn/umeng_analytics_plugin ,
> 可以试试用0.1.8的版本
> lcfarm_flutter_umeng:
> git:
> url: https://github.com/MrLiuYS/lcfarm_flutter_umeng.git
> ref: 0.1.8
> 很抱歉.添麻烦了.

大佬啥时候找个时间看看··解决下这个bug 以前就用你这个库，确实好用 你推荐的库也有问题。

**Comment by Blankeer** [comment]
我现在用的 flutter_fai_umeng，暂时顶着

**Comment by yj229201093** [comment]
> 我现在用的 flutter_fai_umeng，暂时顶着

flutter_fai_umeng iOS和android 都能统计到数据吗

**Comment by Blankeer** [comment]
> > 我现在用的 flutter_fai_umeng，暂时顶着
> 
> flutter_fai_umeng iOS和android 都能统计到数据吗

我试了 android 可以，但是看日志有时候统计不及时，可能应该是友盟的问题，几个 flutter umeng 的我都看了下源码，大同小异

**Comment by yj229201093** [comment]
我看初始化就设置了一个key iOS和android是两个不同的key 哎 好难

**Comment by Blankeer** [comment]
> 我看初始化就设置了一个key iOS和android是两个不同的key 哎 好难

判断平台，然后传对应的 key 就可以了

**Comment by yj229201093** [comment]
谢谢 我试试

**Comment by zhangweiwei0326** [comment]
抽时间搞一下啊 大佬 MissingPluginException (MissingPluginException(No implementation found for method init on channel lcfarm_flutter_umeng))

**Comment by zhangweiwei0326** [comment]
找到问题了 用git引入插件可以，大佬发布到pub的代码pubspec.yaml 少了代码
`plugin:
    androidPackage: com.nongfadai.lcfarm_flutter_umeng
    pluginClass: LcfarmFlutterUmengPlugin`

**Comment by coku00** [comment]
> 找到问题了 用git引入插件可以，大佬发布到pub的代码pubspec.yaml 少了代码
> `plugin: androidPackage: com.nongfadai.lcfarm_flutter_umeng pluginClass: LcfarmFlutterUmengPlugin`
